export const DEFAULT_TAG = "default";
export const DI_CONTAINER_RESOLUTION_CHAIN_NAMESPACE =
  "DI_CONTAINER_RESOLUTION_CHAIN";
export const DI_CONTAINER_REQUEST_SCOPE_NAMESPACE =
  "APIRATORJS_DI_CONTAINER_REQUEST_SCOPE_NAMESPACE";
